spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_AUTH_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

token:
  expiration:
    access-minutes: 10
    refresh-days: 7

camunda.bpm.client:
  base-url: ${CAMUNDA_URL}
  lock-duration: 10000
  async-response-timeout: 750
  subscriptions:
    auth_service_create:
      variable-names: authRequest
  default-serialization-format: application/json

server:
  error:
    include-stacktrace: never
  port: 80

eureka:
  client:
    webclient:
      enabled: false