spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_AUTH_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  error:
    include-stacktrace: never
    include-message: always
  port: 80

token:
  expiration:
    access-minutes: 10
    refresh-days: 7